name: ✨Feature Request
description: Request a new feature or enhancement
labels: ["enhancement"]
title: "[FEAT]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a feature request! 🤗
        Please make sure this feature request hasn't been already submitted by someone by looking through other open/closed issues
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a brief description of the feature or enhancement you would like. 
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information on the feature request like proposed solutions, links, screenshots, etc.

  - type: input
    id: cwm-ticket
    attributes:
      label: CW Manage Ticket ID
      description: If there is a CWM Ticket ID relating to this request, please provide it here. Please make sure to merge and/or bundle all related tickets into one master ticket for easier triage.
      placeholder: "123456"

  - type: input
    id: tracking-issue-reference
    attributes:
      label: Tracking Issue Reference
      description: If there is a tracking issue in GitHub Projects that this feature should be added to, provide the link here. You can shortcut the link by typing ctsnyc/projects-tracking#[ISSUE NUMBER HERE].
